repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.10
      args: [--force-exclude, ignored/]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
-   repo: https://github.com/dimaka-wix/commit-msg-hook.git
    rev: v0.3.4
    hooks:
        - id: commit-msg-hook
          stages: [commit-msg]