DATA:
  BCC: IDR
  END_DATE: 2022-10-20
  MAX_TEST: 15580.5
  MAX_TRAIN: 16718.5
  MIN_TEST: 14064.45
  MIN_TRAIN: 11973.0
  SCC: USD
  START_DATE: 2014-10-20
  TESTING: 0.2
  TRAINING: 0.8
MODEL:
  CHECKPOINT: ''
  DROPOUT: null
  EPOCHS: 100
  HIDDEN_LAYER: 2
  HIDDEN_SIZE:
  - 8
  - 16
  - 32
  - 64
  INPUT_SIZE:
  - 7
  - 8
  - 9
  - 10
  LEARNING_RATE:
  - 0.1
  - 0.01
  - 0.001
  MODEL_NAME: ''
  OPTIM_FUNC: Adam
  OUTPUT_SIZE: 1
TICKERS:
- USDIDR
- JPYIDR
WEIGHT:
  SAVE_BEST: true
  SAVE_WEIGHT_PATH: ./models
