DATA:
  BCC: IDR
  END_DATE: 2023-04-30
  MAX_DATA: 156.061702
  MIN_DATA: 101.255919
  SCC: JPY
  START_DATE: 2014-04-30
  TEST: 0.2
  TRAIN: 0.8
MODEL:
  CHECKPOINT: 
    INPUT: 7
    HIDDEN_1: 64
    HIDDEN_2: 64
    OUTPUT: 1
  DROPOUT: 0.2
  EPOCHS: 100
  HIDDEN_LAYER: 2
  HIDDEN_SIZE:
  - 8
  - 16
  - 32
  - 64
  INPUT_SIZE:
  - 7
  - 14
  - 30
  LEARNING_RATE:
  - 0.1
  - 0.01
  - 0.001
  MODEL_NAME: ''
  OPTIM_FUNC: Adam
  OUTPUT_SIZE: 1
TICKERS:
- USDIDR
- JPYIDR
WEIGHT:
  SAVE_BEST: true
  SAVE_WEIGHT_PATH: ./models
