DATA:
  TRAINING: 0.8
  TESTING: 0.2
  START_DATE: 2014-10-20
  END_DATE: 2022-10-20
  SCC: "JPY"
  BCC: "IDR"
WEIGHT:
  SAVE_BEST: True
  SAVE_WEIGHT_PATH: ./models
MODEL:
  CHECKPOINT: ''
  EPOCHS: 100
  LEARNING_RATE: [0.1, 0.01, 0.001]
  MODEL_NAME: ''
  OPTIM_FUNC: Adam
  INPUT_SIZE: [7, 8, 9, 10]
  OUTPUT_SIZE: 1
  HIDDEN_SIZE: [8, 16, 32, 64]
  HIDDEN_LAYER: 2
  DROPOUT:
TICKERS: ["USDIDR", "JPYIDR"]